// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:113973f2-9d2b-4d25-a798-71c512268cf1',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'rnexpoauth-hosting-mobilehub-458026103',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'daoao8xktw6cd.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f0843b38618f4ef4bf45dad6920ccc9c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '55c01638-f4b9-4750-bfeb-8338bf51ed83',
    'aws_project_name': 'RNExpoAuth',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'rnexpoauth-mobilehub-458026103',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'rnexpoauth-userfiles-mobilehub-458026103',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_lItglS0QG',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '53jknfhif3fhnu12l631d30d0e',
}

export default awsmobile;
